export type Receita = {
  id: number;
  imagem: string;
  nome: string;
  midia: string;
  ingredientes: string[];
  modo_de_preparo: string[];
};

const receitas: Receita[] = [
  {
    id: 1,
    imagem: "/images/padrinhos-magicos.png",
    nome: "Bolinho mágico",
    midia: "Padrinhos mágicos",
    ingredientes: [
      "100 g de manteiga",
      "1 xc e ¼ de açúcar",
      "3 ovos",
      "1 ½ de farinha",
      "½ xc de chocolate em pó",
      "200 ml de leite",
      "1 colher de fermento",
    ],
    modo_de_preparo: [
      "Bata a manteiga o açúcar os ovos e bata bem",
      "Adicione a farinha, o chocolate e o leite e bata até ficar homogêneo",
      "Adicione o fermento",
      "Asse por 15 min",
      "Decore com chantilly rosa",
    ],
  },
  {
    id: 2,
    imagem: "/images/esqueceram-de-mim.jpg",
    nome: "Mac in Cheese",
    midia: "Esqueceram de mim",
    ingredientes: [
      "2 xícaras de macarrão tipo cotovelo",
      "2 colheres de sopa de manteiga",
      "2 colheres de sopa de farinha de trigo",
      "2 xícaras de leite",
      "2 1/2 xícaras de queijo cheddar, ralado",
      "Sal a gosto",
      "Pimenta a gosto",
      "1/2 xícara de migalhas de pão (opcional, para cobertura crocante)",
    ],
    modo_de_preparo: [
      "Cozinhe o macarrão conforme as instruções da embalagem. Escorra e reserve.",
      "Em uma panela grande, derreta a manteiga em fogo médio. Adicione a farinha e mexa continuamente até obter uma mistura homogênea.",
      "Gradualmente, adicione o leite à mistura de manteiga e farinha, mexendo constantemente para evitar a formação de grumos.",
      "Continue mexendo até que a mistura comece a engrossar. Adicione o queijo cheddar ralado e mexa até que esteja completamente derretido e a mistura fique cremosa.",
      "Tempere com sal e pimenta a gosto.",
      "Adicione o macarrão cozido à mistura de queijo, certificando-se de que todos os pedaços de macarrão estejam cobertos com o molho de queijo.",
      "Se desejar uma cobertura crocante, espalhe as migalhas de pão sobre a parte superior do Mac 'n' Cheese.",
      "Pré-aqueça o forno e asse até que a parte superior fique dourada e borbulhante.",
    ],
  },
  {
    id: 3,
    imagem: "/images/noiva-em-fuga.webp",
    nome: "Cookies de Chocolate",
    midia: "Noiva em Fuga",
    ingredientes: [
      "1 xícara (2 sticks) de manteiga, temperatura ambiente",
      "3/4 de xícara de açúcar granulado",
      "3/4 de xícara de açúcar mascavo, compactado",
      "2 ovos",
      "1 colher de chá de extrato de baunilha",
      "2 1/4 xícaras de farinha de trigo",
      "1 colher de chá de bicarbonato de sódio",
      "1/2 colher de chá de sal",
      "2 xícaras de gotas de chocolate",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 180°C. Forre assadeiras com papel-manteiga.",
      "Em uma tigela grande, bata a manteiga, açúcar granulado e açúcar mascavo até obter uma mistura leve e cremosa.",
      "Adicione os ovos, um de cada vez, batendo bem após cada adição. Acrescente a baunilha e misture.",
      "Em outra tigela, misture a farinha, bicarbonato de sódio e sal. Adicione gradualmente à mistura de manteiga até ficar bem combinado.",
      "Adicione as gotas de chocolate e misture bem.",
      "Com uma colher de sorvete ou duas colheres, coloque montinhos de massa na assadeira preparada, deixando espaço entre eles.",
      "Asse no forno pré-aquecido por 10-12 minutos ou até que as bordas fiquem douradas.",
      "Retire do forno e deixe os cookies esfriarem nas assadeiras por alguns minutos antes de transferi-los para uma grade para esfriar completamente.",
    ],
  },
  {
    id: 4,
    imagem: "/images/familia-adams.jpg",
    nome: "Biscoitos das Escoteiras",
    midia: "Quarta-feira Familia Addams",
    ingredientes: [
      "1 xícara (2 sticks) de manteiga, temperatura ambiente",
      "1/2 xícara de açúcar",
      "2 xícaras de farinha de trigo",
      "1/4 de colher de chá de sal",
      "1 colher de chá de essência de baunilha",
      "1/2 xícara de chocolate derretido (para decorar)",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 180°C. Forre assadeiras com papel-manteiga.",
      "Em uma tigela grande, bata a manteiga e o açúcar até obter uma mistura leve e fofa.",
      "Adicione a farinha, o sal e a essência de baunilha. Misture até formar uma massa homogênea.",
      "Em uma superfície enfarinhada, abra a massa com um rolo até obter uma espessura de cerca de 0,5 cm.",
      "Use cortadores de biscoito para cortar a massa em formatos desejados.",
      "Transfira os biscoitos para as assadeiras preparadas e leve ao forno pré-aquecido por 10-12 minutos ou até que as bordas comecem a dourar.",
      "Retire do forno e deixe esfriar completamente nas assadeiras.",
      "Depois de esfriar, decore os biscoitos com chocolate derretido, se desejar.",
    ],
  },
  {
    id: 5,
    imagem: "/images/costela-a-jay.jpg",
    nome: "Costela à Jay",
    midia: "Modern Family",
    ingredientes: [
      "2 racks de costela de porco",
      "1 xícara de molho barbecue (use seu favorito)",
      "1/4 de xícara de mostarda",
      "1/4 de xícara de mel",
      "2 colheres de sopa de molho de soja",
      "2 colheres de sopa de alho picado",
      "1 colher de sopa de pimenta preta",
      "1 colher de sopa de páprica defumada",
      "1 colher de chá de sal",
      "1/2 colher de chá de pimenta caiena (opcional, para um toque picante)",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 180°C.",
      "Tempere as costelas com sal, pimenta e páprica defumada.",
      "Em uma tigela, misture o molho barbecue, mostarda, mel, molho de soja, alho e pimenta preta. Se desejar um toque picante, adicione a pimenta caiena.",
      "Pincele generosamente as costelas com a mistura de molho barbecue em ambos os lados.",
      "Embrulhe cada rack de costela em papel alumínio.",
      "Coloque as costelas embrulhadas em uma assadeira e asse no forno por cerca de 2 horas, ou até que a carne esteja macia e cozida.",
      "Retire as costelas do papel alumínio e coloque-as de volta no forno por mais 20-30 minutos para dourar.",
      "Quando estiverem prontas, retire as costelas do forno e deixe descansar por alguns minutos.",
      "Corte as costelas entre os ossos e sirva com o molho adicional.",
    ],
  },
  {
    id: 6,
    imagem: "/images/frango-assado-ao-estilo-dos-anos-50.jpg",
    nome: "Frango Assado ao Estilo dos Anos 50",
    midia: "De volta para o futuro",
    ingredientes: [
      "4 pedaços de coxa de frango",
      "Sal e pimenta a gosto",
      "2 colheres de sopa de manteiga",
      "1/2 xícara de caldo de galinha",
      "1 colher de chá de páprica",
      "1 colher de chá de alho em pó",
      "1 colher de chá de cebola em pó",
      "1 colher de chá de orégano seco",
      "1/2 xícara de creme de leite",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 180°C.",
      "Tempere as coxas de frango com sal e pimenta a gosto.",
      "Em uma frigideira grande, derreta a manteiga em fogo médio-alto.",
      "Adicione as coxas de frango à frigideira e doure todos os lados.",
      "Remova o frango da frigideira e reserve.",
      "Na mesma frigideira, adicione o caldo de galinha, a páprica, o alho em pó, a cebola em pó e o orégano. Mexa bem.",
      "Coloque as coxas de frango de volta na frigideira, cobrindo-as com a mistura de temperos.",
      "Asse no forno pré-aquecido por aproximadamente 30-35 minutos, ou até que o frango esteja cozido.",
      "Durante os últimos 10 minutos de cozimento, regue o frango com o creme de leite para criar um molho cremoso.",
      "Retire do forno, deixe descansar por alguns minutos e sirva.",
    ],
  },
  {
    id: 7,
    imagem: "/images/torta-escocesa.webp",
    nome: "Torta escocesa",
    midia: "Pica Pau",
    ingredientes: [
      "bolachada amanteigada",
      "manteiga",
      "3 colheres de sopa de manteiga",
      "3 colheres de sopa de farinha",
      "3/4 de xícara de açúcar mascavo",
      "1 xícara de leite",
      "1 gema",
      "pitada de sal",
      "1 colher de chá de essência de baunilha",
    ],
    modo_de_preparo: [
      "Misture bolacha triturada com manteiga derretida e forre uma forma.",
      "Em uma panela derreta 3 colheres de manteiga, 3 de farinha misture bem e coloque ¾ de xicara de açúcar mascavo e uma de leite.",
      "Despeja uma gema mistura tudo e peneira em uma panela.",
      "Acrescenta uma pitada de sal e essência de baunilha.",
      "Leve ao fogo até engrossar.",
      "Despeje na forma e leve para o forno por 15 minutos.",
      "Cubra com chocolate derretido.",
    ],
  },
  {
    id: 8,
    imagem: "/images/salada-caesar.jpg",
    nome: "Salada Caesar",
    midia: "As Branquelas",
    ingredientes: [
      "Alface romana, lavada e rasgada",
      "Croutons",
      "Queijo parmesão ralado",
      "Para o Molho Caesar:",
      "1/2 xícara de maionese",
      "2 colheres de sopa de azeite de oliva",
      "2 colheres de chá de mostarda Dijon",
      "2 colheres de chá de suco de limão fresco",
      "2 dentes de alho, picados",
      "1/4 xícara de queijo parmesão ralado",
      "Sal e pimenta a gosto",
    ],
    modo_de_preparo: [
      "Em uma tigela grande, coloque as folhas de alface romana lavadas.",
      "Adicione croutons por cima da alface.",
      "Polvilhe generosamente com queijo parmesão ralado.",
      "Em uma tigela pequena, misture a maionese, azeite de oliva, mostarda Dijon, suco de limão, alho picado e queijo parmesão ralado.",
      "Tempere com sal e pimenta a gosto e misture bem.",
      "Despeje o molho Caesar sobre a salada e misture delicadamente para garantir que todas as folhas de alface estejam revestidas.",
      "Sirva imediatamente, adicionando mais croutons e queijo parmesão por cima, se desejar.",
    ],
  },
  {
    id: 9,
    imagem: "/images/canelones-a-moda-italiana.jpg",
    nome: "Canelones à Moda Italiana",
    midia: "Os Bons Companheiros",
    ingredientes: [
      "Para a Massa dos Canelones:",
      "200g de massa para canelones (pré-cozida conforme as instruções da embalagem)",
      "Sal (para temperar a água de cozimento)",
      "Para o Recheio:",
      "500g de carne moída (porco, boi ou uma mistura)",
      "1 cebola, picada",
      "2 dentes de alho, picados",
      "1 xícara de espinafre fresco, picado",
      "1 xícara de ricota",
      "1/2 xícara de queijo parmesão ralado",
      "1 ovo",
      "Sal e pimenta a gosto",
      "Para o Molho de Tomate:",
      "800g de tomates pelados, amassados",
      "2 colheres de sopa de azeite de oliva",
      "1 cebola, picada",
      "2 dentes de alho, picados",
      "1 colher de chá de orégano seco",
      "Sal e pimenta a gosto",
      "Para a Cobertura:",
      "1 xícara de queijo mussarela, ralado",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 180°C.",
      "Cozinhe a massa para canelones em água salgada conforme as instruções da embalagem. Escorra e reserve.",
      "Em uma panela, aqueça o azeite de oliva e refogue a cebola e o alho até ficarem dourados.",
      "Adicione a carne moída à panela e cozinhe até dourar. Tempere com sal e pimenta.",
      "Acrescente o espinafre e cozinhe até murchar.",
      "Em uma tigela grande, misture a carne e o espinafre com a ricota, queijo parmesão e ovo. Tempere a gosto.",
      "Recheie cada canelone com a mistura preparada.",
      "Em uma panela, aqueça o azeite de oliva para o molho de tomate. Adicione a cebola e o alho, refogando até ficarem macios.",
      "Adicione os tomates pelados amassados e o orégano. Tempere com sal e pimenta. Cozinhe por cerca de 15 minutos.",
      "Espalhe um pouco do molho de tomate no fundo de uma assadeira.",
      "Coloque os canelones recheados na assadeira e cubra com o restante do molho de tomate.",
      "Polvilhe o queijo mussarela por cima dos canelones.",
      "Asse no forno pré-aquecido por 25-30 minutos ou até que o queijo esteja dourado e borbulhante.",
      "Retire do forno e deixe descansar por alguns minutos antes de servir.",
    ],
  },
  {
    id: 10,
    imagem: "/images/cubanos.jpg",
    nome: "Cubanos (sanduíche de porco assado)",
    midia: "Chef",
    ingredientes: [
      "Pão para cubanos",
      "Pernil de porco",
      "Presunto",
      "Queijo suíço",
      "Mostarda",
      "Picles",
      "Manteiga",
    ],
    modo_de_preparo: [
      "Asse o pernil de porco lentamente até ficar macio e desfiável.",
      "Monte os sanduíches com pernil, presunto, queijo, mostarda e picles.",
      "Grelhe os sanduíches na manteiga até que o queijo derreta e o pão fique dourado.",
    ],
  },
  {
    id: 11,
    imagem: "/images/sufle-de-queijo.webp",
    nome: "Sufle de Queijo",
    midia: "A Bela e a Fera",
    ingredientes: [
      "3 colheres de sopa de manteiga",
      "1/4 xícara de farinha de trigo",
      "1 xícara de leite",
      "1 1/2 xícaras de queijo gruyère ralado",
      "1/2 xícara de queijo parmesão ralado",
      "4 gemas de ovos",
      "5 claras de ovos",
      "Sal e pimenta a gosto",
      "Noz-moscada (opcional)",
    ],
    modo_de_preparo: [
      "Pré-aqueça o forno a 190°C. Unte levemente ramequins individuais.",
      "Em uma panela, derreta a manteiga em fogo médio. Adicione a farinha de trigo e mexa até formar uma pasta.",
      "Gradualmente, adicione o leite, mexendo constantemente para evitar grumos. Cozinhe até que a mistura engrosse.",
      "Retire a panela do fogo e adicione os queijos ralados, mexendo até que estejam completamente derretidos.",
      "Deixe a mistura esfriar um pouco e adicione as gemas de ovos, uma de cada vez. Tempere com sal, pimenta e noz-moscada, se desejar.",
      "Em uma tigela separada, bata as claras de ovo até formar picos firmes.",
      "Delicadamente, incorpore as claras de ovo na mistura de queijo.",
      "Coloque a mistura nos ramequins preparados e asse no forno pré-aquecido por 20-25 minutos, ou até que os sufles estejam dourados e inchados.",
    ],
  },
  {
    id: 12,
    imagem: "/images/tostadas-doces-da-tiana.jpg",
    nome: "Tostadas Doces da Tiana",
    midia: "A Princesa e o Sapo",
    ingredientes: [
      "4 tortilhas de trigo ou milho",
      "2 bananas maduras, cortadas em rodelas",
      "2 colheres de sopa de manteiga",
      "2 colheres de sopa de açúcar mascavo",
      "1 colher de chá de canela em pó",
      "Mel para regar",
      "Sorvete de baunilha (opcional, para servir)",
    ],
    modo_de_preparo: [
      "Em uma frigideira, derreta a manteiga em fogo médio.",
      "Adicione as rodelas de banana à frigideira e polvilhe com açúcar mascavo e canela.",
      "Cozinhe as bananas por alguns minutos até que estejam caramelizadas, mexendo ocasionalmente. Reserve.",
      "Grelhe as tortilhas até que fiquem levemente douradas.",
      "Coloque as bananas caramelizadas sobre as tortilhas grelhadas.",
      "Regue com mel a gosto.",
      "Se desejar, sirva as tostadas doces com uma bola de sorvete de baunilha.",
    ],
  },
  {
    id: 13,
    imagem: "/images/elixir-di-amore.jpg",
    nome: "Elixir di Amore",
    midia: "Grand Budapest Hotel",
    ingredientes: [
      "1 1/2 oz de Gin",
      "3/4 oz de Licor de Flor de Sabugueiro",
      "1/2 oz de Vermute Seco",
      "1/2 oz de Suco de Limão",
      "Clara de ovo (opcional)",
    ],
    modo_de_preparo: [
      "Adicione todos os ingredientes a uma coqueteleira com gelo.",
      "Agite bem.",
      "Coe para um copo gelado.",
    ],
  },
  {
    id: 14,
    imagem: "/images/daiquiri.webp",
    nome: "Daiquiri",
    midia: "James Bond (Dr. No)",
    ingredientes: [
      "2 oz de Rum Branco",
      "3/4 oz de Suco de Limão",
      "1/2 oz de Xarope de Açúcar",
    ],
    modo_de_preparo: [
      "Misture todos os ingredientes em uma coqueteleira com gelo.",
      "Agite bem.",
      "Coe para uma taça de coquetel.",
    ],
  },
  {
    id: 15,
    imagem: "/images/salmiakki-koskenkorva.jpg",
    nome: "Salmiakki Koskenkorva",
    midia: "Iron Sky",
    ingredientes: [
      "1 oz de Vodka de Salmiakki (ou vodka com sabor de salmiakki/licorice)",
      "1 oz de Licor de Café",
    ],
    modo_de_preparo: [
      "Despeje a vodka de salmiakki e o licor de café em um copo com gelo.",
      "Mexa suavemente e sirva.",
    ],
  },
  {
    id: 16,
    imagem: "/images/mai-tai.jpg",
    nome: "Mai Tai",
    midia: "De Volta Para o Futuro II",
    ingredientes: [
      "1 1/2 oz de Rum Branco",
      "1/2 oz de Rum Envelhecido",
      "1 oz de Curacao de Laranja",
      "3/4 oz de xarope de amêndoa",
      "Suco de limão",
    ],
    modo_de_preparo: [
      "Adicione todos os ingredientes em uma coqueteleira com gelo.",
      "Agite bem e coe em um copo com gelo.",
    ],
  },
  {
    id: 17,
    imagem: "/images/margarita.webp",
    nome: "Margarita",
    midia: "Os Bons Companheiros",
    ingredientes: [
      "2 oz de Tequila",
      "1 oz de Triple Sec",
      "3/4 oz de Suco de Limão",
    ],
    modo_de_preparo: [
      "Esfregue a borda do copo com uma fatia de limão e mergulhe-a em sal para criar a borda salgada (opcional).",
      "Adicione todos os ingredientes em uma coqueteleira com gelo.",
      "Agite bem e coe em um copo com gelo.",
    ],
  },
  {
    id: 18,
    imagem: "/images/cosmopolitan.jpg",
    nome: "Cosmopolitan",
    midia: "Sex and the City",
    ingredientes: [
      "1 1/2 oz de Vodka de Citrus",
      "1 oz de Triple Sec",
      "1/2 oz de Suco de Cranberry",
      "Suco de meio limão",
    ],
    modo_de_preparo: [
      "Adicione todos os ingredientes em uma coqueteleira com gelo.",
      "Agite bem e coe em uma taça de coquetel.",
    ],
  },
  {
    id: 19,
    imagem: "/images/alabama-slammer.jpg",
    nome: "Alabama Slammer",
    midia: "A Última Noite de Solteiro",
    ingredientes: [
      "1 oz de Amaretto",
      "1 oz de Licor de Pêssego",
      "1 oz de Sloe Gin",
      "Suco de laranja",
    ],
    modo_de_preparo: [
      "Adicione Amaretto, Licor de Pêssego e Sloe Gin em um copo com gelo.",
      "Complete com suco de laranja.",
      "Mexa suavemente e decore com uma fatia de laranja.",
    ],
  },
  {
    id: 20,
    imagem: "/images/suco-de-maca-encantado.jpg",
    nome: "Suco de Maçã Encantado",
    midia: "Branca de Neve",
    ingredientes: [
      "2 maçãs vermelhas, descascadas e picadas",
      "1/2 colher de chá de canela em pó",
      "1 colher de chá de mel",
      "Gelo a gosto",
    ],
    modo_de_preparo: [
      "Bata as maçãs no liquidificador até obter um purê.",
      "Adicione a canela e o mel, e bata novamente.",
      "Coe a mistura para remover polpa.",
      "Sirva sobre gelo e decore com uma fatia de maçã.",
    ],
  },
  {
    id: 21,
    imagem: "/images/limonaide-de-framboesa.jpg",
    nome: "Limonaide de Framboesa",
    midia: "Phineas e Ferb",
    ingredientes: [
      "1 xícara de framboesas frescas",
      "1 xícara de suco de limão fresco",
      "1/2 xícara de açúcar",
      "3 xícaras de água fria",
      "Gelo a gosto",
    ],
    modo_de_preparo: [
      "Em uma panela, faça uma calda de açúcar aquecendo o açúcar e 1 xícara de água até dissolver.",
      "Em um liquidificador, misture as framboesas com o suco de limão.",
      "Coe para remover as sementes.",
      "Combine a calda de açúcar, a mistura de framboesa e a água restante.",
      "Sirva gelado sobre gelo.",
    ],
  },
  {
    id: 22,
    imagem: "/images/cafe-gelado-com-leite-de-amendoas.webp",
    nome: "Café Gelado com Leite de Amêndoas Café Gelado com Leite de Amêndoas",
    midia: "A Dama e o Vagabundo",
    ingredientes: [
      "1 xícara de café forte, resfriado",
      "1/2 xícara de leite de amêndoas",
      "1 colher de sopa de xarope de baunilha",
      "Gelo a gosto",
    ],
    modo_de_preparo: [
      "Misture o café resfriado com o leite de amêndoas.",
      "Adoce com xarope de baunilha.",
      "Sirva sobre gelo.",
    ],
  },
  {
    id: 23,
    imagem: "/images/suco-de-laranja-com-gas.webp",
    nome: "Suco de Laranja com Gás",
    midia: "Os Flintstones",
    ingredientes: [
      "2 xícaras de suco de laranja fresco",
      "Água com gás",
      "Fatias de laranja para decorar",
      "Gelo a gosto",
    ],
    modo_de_preparo: [
      "Divida o suco de laranja entre os copos.",
      "Complete com água com gás.",
      "Adicione gelo e decore com fatias de laranja.",
    ],
  },
  {
    id: 24,
    imagem: "/images/cha-de-jasmin.gif",
    nome: "Chá de Jasmim",
    midia: "Mulan",
    ingredientes: [
      "1 saquinho de chá de jasmim",
      "1 xícara de água quente",
      "Mel a gosto",
      "Fatia de limão para decorar",
    ],
    modo_de_preparo: [
      "Faça o chá de jasmim deixando o saquinho de chá em água quente por alguns minutos.",
      "Adoce com mel a gosto.",
      "Decore com uma fatia de limão.",
    ],
  },
  {
    id: 25,
    imagem: "/images/chocolate-quente.webp",
    nome: "Chocolate Quente",
    midia: "A Fantástica Fábrica de Chocolate",
    ingredientes: [
      "2 xícaras de leite",
      "2 colheres de sopa de cacau em pó",
      "2 colheres de sopa de açúcar",
      "1/2 colher de chá de essência de baunilha",
      "Marshmallows para decorar",
    ],
    modo_de_preparo: [
      "Aqueça o leite em uma panela.",
      "Em uma tigela pequena, misture o cacau em pó e o açúcar.",
      "Adicione a mistura de cacau ao leite quente, mexendo bem.",
      "Acrescente a essência de baunilha.",
      "Despeje em canecas e decore com marshmallows.",
    ],
  },
];

export default receitas;
